api = "0.2"

[buildpack]
  id = "paketo-onboarding/node-engine"
  name = "Onboarding Node Engine Buildpack"
  version = "0.0.1"

[metadata]
  [[metadata.dependencies]]
    id = "node"
    sha256 = "f9de81daeec972c44502537c97edb7bc0b0c1ea8a797e12c188e7f9a17e61d4c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.5.0_linux_x64_cflinuxfs3_f9de81da.tgz"
    version = "14.5.0"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
